#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

$application = new Symfony\Component\Console\Application();
$application->add(new \EloGank\Api\Command\ApiStartCommand());
$application->run();