routes:
  summonerService:
    getSummonerByName:                   [summonerName]
    getAllSummonerDataByAccount:         [accountId]
    getAllPublicSummonerDataByAccount:   [accountId]
    getSummonerInternalNameByName:       [summonerName]
    getSummonerNames:                    ["summonerIds[]"]

  playerStatsService:
    getAggregatedStats:                  [accountId, "gameMode (CLASSIC, ODIN, ARAM)", "seasonId (1-4)"]
    getRecentGames:                      [accountId]
    retrieveTopPlayedChampions:          [accountId, "gameMode (CLASSIC, ODIN, ARAM)"]
    getTeamAggregatedStats:              [teamId]
    getTeamEndOfGameStats:               [teamId, gameId]
    retrievePlayerStatsByAccountId:      [accountId, "seasonId (1-4)"]

  spellBookService:
    getSpellBook:                        [summonerId]

  masteryBookService:
    getMasteryBook:                      [summonerId]

  inventoryService:
    getAvailableChampions:               []

  summonerIconService:
    getSummonerIconInventory:            [summonerId]

  gameService:
    retrieveInProgressSpectatorGameInfo: [summonerName]

  leaguesServiceProxy:
    getAllLeaguesForPlayer:              [summonerId]
    getChallengerLeague:                 ["queueName (RANKED_SOLO_5x5, RANKED_TEAM_5x5, RANKED_TEAM_3x3)"]

  loginService:
    getStoreUrl:                         []