log:
  path: logs/api.log
  verbosity: debug

client:
  version: 4.3.x
  locale: en_US
  accounts:
    EUW:
      username: username
      password: password

region:
  class: EloGank\Api\Region\Region
  servers:
    NA:
      name:       North America
      server:     prod.na1.lol.riotgames.com
      loginQueue: lq.na1.lol.riotgames.com
    EUW:
      name:       Europe West
      server:     prod.eu.lol.riotgames.com
      loginQueue: lq.eu.lol.riotgames.com