regions:
  NA:
    name:       North America
    server:     prod.na1.lol.riotgames.com
    loginQueue: lq.na1.lol.riotgames.com
  EUW:
    name:       Europe West
    server:     prod.eu.lol.riotgames.com
    loginQueue: lq.eu.lol.riotgames.com